var annotated_dup =
[
    [ "BPMNOS", "namespaceBPMNOS.html", [
      [ "Execution", "namespaceBPMNOS_1_1Execution.html", [
        [ "Color", "namespaceBPMNOS_1_1Execution_1_1Color.html", [
          [ "Modifier", "classBPMNOS_1_1Execution_1_1Color_1_1Modifier.html", "classBPMNOS_1_1Execution_1_1Color_1_1Modifier" ]
        ] ],
        [ "ascending", "structBPMNOS_1_1Execution_1_1ascending.html", "structBPMNOS_1_1Execution_1_1ascending" ],
        [ "auto_list", "classBPMNOS_1_1Execution_1_1auto__list.html", "classBPMNOS_1_1Execution_1_1auto__list" ],
        [ "auto_set", "classBPMNOS_1_1Execution_1_1auto__set.html", "classBPMNOS_1_1Execution_1_1auto__set" ],
        [ "CachedCandidates", "classBPMNOS_1_1Execution_1_1CachedCandidates.html", "classBPMNOS_1_1Execution_1_1CachedCandidates" ],
        [ "Candidates", "classBPMNOS_1_1Execution_1_1Candidates.html", "classBPMNOS_1_1Execution_1_1Candidates" ],
        [ "ChoiceDecision", "structBPMNOS_1_1Execution_1_1ChoiceDecision.html", "structBPMNOS_1_1Execution_1_1ChoiceDecision" ],
        [ "ChoiceEvent", "structBPMNOS_1_1Execution_1_1ChoiceEvent.html", "structBPMNOS_1_1Execution_1_1ChoiceEvent" ],
        [ "ClockTickEvent", "structBPMNOS_1_1Execution_1_1ClockTickEvent.html", "structBPMNOS_1_1Execution_1_1ClockTickEvent" ],
        [ "CompetingCandidates", "classBPMNOS_1_1Execution_1_1CompetingCandidates.html", "classBPMNOS_1_1Execution_1_1CompetingCandidates" ],
        [ "CompletionEvent", "structBPMNOS_1_1Execution_1_1CompletionEvent.html", "structBPMNOS_1_1Execution_1_1CompletionEvent" ],
        [ "ConditionalEventObserver", "classBPMNOS_1_1Execution_1_1ConditionalEventObserver.html", "classBPMNOS_1_1Execution_1_1ConditionalEventObserver" ],
        [ "Controller", "classBPMNOS_1_1Execution_1_1Controller.html", "classBPMNOS_1_1Execution_1_1Controller" ],
        [ "DataUpdate", "structBPMNOS_1_1Execution_1_1DataUpdate.html", "structBPMNOS_1_1Execution_1_1DataUpdate" ],
        [ "Decision", "classBPMNOS_1_1Execution_1_1Decision.html", "classBPMNOS_1_1Execution_1_1Decision" ],
        [ "DecisionRequest", "structBPMNOS_1_1Execution_1_1DecisionRequest.html", "structBPMNOS_1_1Execution_1_1DecisionRequest" ],
        [ "descending", "structBPMNOS_1_1Execution_1_1descending.html", "structBPMNOS_1_1Execution_1_1descending" ],
        [ "Engine", "classBPMNOS_1_1Execution_1_1Engine.html", "classBPMNOS_1_1Execution_1_1Engine" ],
        [ "EntryDecision", "structBPMNOS_1_1Execution_1_1EntryDecision.html", "structBPMNOS_1_1Execution_1_1EntryDecision" ],
        [ "EntryEvent", "structBPMNOS_1_1Execution_1_1EntryEvent.html", "structBPMNOS_1_1Execution_1_1EntryEvent" ],
        [ "ErrorEvent", "structBPMNOS_1_1Execution_1_1ErrorEvent.html", "structBPMNOS_1_1Execution_1_1ErrorEvent" ],
        [ "Evaluation", "structBPMNOS_1_1Execution_1_1Evaluation.html", "structBPMNOS_1_1Execution_1_1Evaluation" ],
        [ "Evaluator", "classBPMNOS_1_1Execution_1_1Evaluator.html", "classBPMNOS_1_1Execution_1_1Evaluator" ],
        [ "Event", "structBPMNOS_1_1Execution_1_1Event.html", "structBPMNOS_1_1Execution_1_1Event" ],
        [ "EventDispatcher", "classBPMNOS_1_1Execution_1_1EventDispatcher.html", "classBPMNOS_1_1Execution_1_1EventDispatcher" ],
        [ "EventListener", "classBPMNOS_1_1Execution_1_1EventListener.html", "classBPMNOS_1_1Execution_1_1EventListener" ],
        [ "ExitDecision", "structBPMNOS_1_1Execution_1_1ExitDecision.html", "structBPMNOS_1_1Execution_1_1ExitDecision" ],
        [ "ExitEvent", "structBPMNOS_1_1Execution_1_1ExitEvent.html", "structBPMNOS_1_1Execution_1_1ExitEvent" ],
        [ "FirstBisectionalChoice", "classBPMNOS_1_1Execution_1_1FirstBisectionalChoice.html", "classBPMNOS_1_1Execution_1_1FirstBisectionalChoice" ],
        [ "FirstEnumeratedChoice", "classBPMNOS_1_1Execution_1_1FirstEnumeratedChoice.html", "classBPMNOS_1_1Execution_1_1FirstEnumeratedChoice" ],
        [ "FirstFeasibleEntry", "classBPMNOS_1_1Execution_1_1FirstFeasibleEntry.html", "classBPMNOS_1_1Execution_1_1FirstFeasibleEntry" ],
        [ "FirstFeasibleExit", "classBPMNOS_1_1Execution_1_1FirstFeasibleExit.html", "classBPMNOS_1_1Execution_1_1FirstFeasibleExit" ],
        [ "FirstMatchingMessageDelivery", "classBPMNOS_1_1Execution_1_1FirstMatchingMessageDelivery.html", "classBPMNOS_1_1Execution_1_1FirstMatchingMessageDelivery" ],
        [ "FlattenedGraph", "classBPMNOS_1_1Execution_1_1FlattenedGraph.html", "classBPMNOS_1_1Execution_1_1FlattenedGraph" ],
        [ "GreedyController", "classBPMNOS_1_1Execution_1_1GreedyController.html", "classBPMNOS_1_1Execution_1_1GreedyController" ],
        [ "GreedyDispatcher", "classBPMNOS_1_1Execution_1_1GreedyDispatcher.html", "classBPMNOS_1_1Execution_1_1GreedyDispatcher" ],
        [ "GuidedEvaluator", "classBPMNOS_1_1Execution_1_1GuidedEvaluator.html", "classBPMNOS_1_1Execution_1_1GuidedEvaluator" ],
        [ "InstantDirectMessage", "classBPMNOS_1_1Execution_1_1InstantDirectMessage.html", "classBPMNOS_1_1Execution_1_1InstantDirectMessage" ],
        [ "InstantEntry", "classBPMNOS_1_1Execution_1_1InstantEntry.html", "classBPMNOS_1_1Execution_1_1InstantEntry" ],
        [ "InstantExit", "classBPMNOS_1_1Execution_1_1InstantExit.html", "classBPMNOS_1_1Execution_1_1InstantExit" ],
        [ "is_weak_ptr", "structBPMNOS_1_1Execution_1_1is__weak__ptr.html", null ],
        [ "is_weak_ptr< std::weak_ptr< T > >", "structBPMNOS_1_1Execution_1_1is__weak__ptr_3_01std_1_1weak__ptr_3_01T_01_4_01_4.html", null ],
        [ "LocalEvaluator", "classBPMNOS_1_1Execution_1_1LocalEvaluator.html", "classBPMNOS_1_1Execution_1_1LocalEvaluator" ],
        [ "Mediator", "structBPMNOS_1_1Execution_1_1Mediator.html", null ],
        [ "Message", "classBPMNOS_1_1Execution_1_1Message.html", "classBPMNOS_1_1Execution_1_1Message" ],
        [ "MessageDeliveries", "classBPMNOS_1_1Execution_1_1MessageDeliveries.html", "classBPMNOS_1_1Execution_1_1MessageDeliveries" ],
        [ "MessageDeliveryDecision", "structBPMNOS_1_1Execution_1_1MessageDeliveryDecision.html", "structBPMNOS_1_1Execution_1_1MessageDeliveryDecision" ],
        [ "MessageDeliveryEvent", "structBPMNOS_1_1Execution_1_1MessageDeliveryEvent.html", "structBPMNOS_1_1Execution_1_1MessageDeliveryEvent" ],
        [ "Metronome", "classBPMNOS_1_1Execution_1_1Metronome.html", "classBPMNOS_1_1Execution_1_1Metronome" ],
        [ "MyopicDecisionTaskTerminator", "classBPMNOS_1_1Execution_1_1MyopicDecisionTaskTerminator.html", "classBPMNOS_1_1Execution_1_1MyopicDecisionTaskTerminator" ],
        [ "MyopicMessageTaskTerminator", "classBPMNOS_1_1Execution_1_1MyopicMessageTaskTerminator.html", "classBPMNOS_1_1Execution_1_1MyopicMessageTaskTerminator" ],
        [ "Notifier", "classBPMNOS_1_1Execution_1_1Notifier.html", "classBPMNOS_1_1Execution_1_1Notifier" ],
        [ "Observable", "structBPMNOS_1_1Execution_1_1Observable.html", "structBPMNOS_1_1Execution_1_1Observable" ],
        [ "Observer", "classBPMNOS_1_1Execution_1_1Observer.html", "classBPMNOS_1_1Execution_1_1Observer" ],
        [ "OutcomeSentinel", "classBPMNOS_1_1Execution_1_1OutcomeSentinel.html", "classBPMNOS_1_1Execution_1_1OutcomeSentinel" ],
        [ "RandomChoice", "classBPMNOS_1_1Execution_1_1RandomChoice.html", "classBPMNOS_1_1Execution_1_1RandomChoice" ],
        [ "ReadyEvent", "structBPMNOS_1_1Execution_1_1ReadyEvent.html", "structBPMNOS_1_1Execution_1_1ReadyEvent" ],
        [ "ReadyHandler", "classBPMNOS_1_1Execution_1_1ReadyHandler.html", "classBPMNOS_1_1Execution_1_1ReadyHandler" ],
        [ "Recorder", "classBPMNOS_1_1Execution_1_1Recorder.html", "classBPMNOS_1_1Execution_1_1Recorder" ],
        [ "ScenarioUpdater", "classBPMNOS_1_1Execution_1_1ScenarioUpdater.html", "classBPMNOS_1_1Execution_1_1ScenarioUpdater" ],
        [ "SeededController", "classBPMNOS_1_1Execution_1_1SeededController.html", "classBPMNOS_1_1Execution_1_1SeededController" ],
        [ "SeededGreedyController", "classBPMNOS_1_1Execution_1_1SeededGreedyController.html", "classBPMNOS_1_1Execution_1_1SeededGreedyController" ],
        [ "SequentialEntries", "classBPMNOS_1_1Execution_1_1SequentialEntries.html", "classBPMNOS_1_1Execution_1_1SequentialEntries" ],
        [ "SequentialPerformerUpdate", "structBPMNOS_1_1Execution_1_1SequentialPerformerUpdate.html", "structBPMNOS_1_1Execution_1_1SequentialPerformerUpdate" ],
        [ "StateMachine", "classBPMNOS_1_1Execution_1_1StateMachine.html", "classBPMNOS_1_1Execution_1_1StateMachine" ],
        [ "SystemState", "classBPMNOS_1_1Execution_1_1SystemState.html", "classBPMNOS_1_1Execution_1_1SystemState" ],
        [ "TaskCompletionHandler", "classBPMNOS_1_1Execution_1_1TaskCompletionHandler.html", "classBPMNOS_1_1Execution_1_1TaskCompletionHandler" ],
        [ "TerminationEvent", "structBPMNOS_1_1Execution_1_1TerminationEvent.html", "structBPMNOS_1_1Execution_1_1TerminationEvent" ],
        [ "TimerEvent", "structBPMNOS_1_1Execution_1_1TimerEvent.html", "structBPMNOS_1_1Execution_1_1TimerEvent" ],
        [ "TimeWarp", "classBPMNOS_1_1Execution_1_1TimeWarp.html", "classBPMNOS_1_1Execution_1_1TimeWarp" ],
        [ "Token", "classBPMNOS_1_1Execution_1_1Token.html", "classBPMNOS_1_1Execution_1_1Token" ]
      ] ],
      [ "Model", "namespaceBPMNOS_1_1Model.html", [
        [ "Attribute", "classBPMNOS_1_1Model_1_1Attribute.html", "classBPMNOS_1_1Model_1_1Attribute" ],
        [ "AttributeRegistry", "classBPMNOS_1_1Model_1_1AttributeRegistry.html", "classBPMNOS_1_1Model_1_1AttributeRegistry" ],
        [ "Choice", "classBPMNOS_1_1Model_1_1Choice.html", "classBPMNOS_1_1Model_1_1Choice" ],
        [ "Conditions", "classBPMNOS_1_1Model_1_1Conditions.html", "classBPMNOS_1_1Model_1_1Conditions" ],
        [ "Content", "classBPMNOS_1_1Model_1_1Content.html", "classBPMNOS_1_1Model_1_1Content" ],
        [ "DataProvider", "classBPMNOS_1_1Model_1_1DataProvider.html", "classBPMNOS_1_1Model_1_1DataProvider" ],
        [ "DecisionTask", "classBPMNOS_1_1Model_1_1DecisionTask.html", "classBPMNOS_1_1Model_1_1DecisionTask" ],
        [ "DeferredDisclosure", "structBPMNOS_1_1Model_1_1DeferredDisclosure.html", "structBPMNOS_1_1Model_1_1DeferredDisclosure" ],
        [ "DeferredInitialization", "structBPMNOS_1_1Model_1_1DeferredInitialization.html", "structBPMNOS_1_1Model_1_1DeferredInitialization" ],
        [ "DynamicDataProvider", "classBPMNOS_1_1Model_1_1DynamicDataProvider.html", "classBPMNOS_1_1Model_1_1DynamicDataProvider" ],
        [ "DynamicScenario", "classBPMNOS_1_1Model_1_1DynamicScenario.html", "classBPMNOS_1_1Model_1_1DynamicScenario" ],
        [ "ExpectedValueDataProvider", "classBPMNOS_1_1Model_1_1ExpectedValueDataProvider.html", "classBPMNOS_1_1Model_1_1ExpectedValueDataProvider" ],
        [ "ExpectedValueScenario", "classBPMNOS_1_1Model_1_1ExpectedValueScenario.html", "classBPMNOS_1_1Model_1_1ExpectedValueScenario" ],
        [ "Expression", "classBPMNOS_1_1Model_1_1Expression.html", "classBPMNOS_1_1Model_1_1Expression" ],
        [ "ExtensionElements", "classBPMNOS_1_1Model_1_1ExtensionElements.html", "classBPMNOS_1_1Model_1_1ExtensionElements" ],
        [ "Gatekeeper", "classBPMNOS_1_1Model_1_1Gatekeeper.html", "classBPMNOS_1_1Model_1_1Gatekeeper" ],
        [ "Guidance", "classBPMNOS_1_1Model_1_1Guidance.html", "classBPMNOS_1_1Model_1_1Guidance" ],
        [ "Input", "structBPMNOS_1_1Model_1_1Input.html", "structBPMNOS_1_1Model_1_1Input" ],
        [ "LookupTable", "classBPMNOS_1_1Model_1_1LookupTable.html", "classBPMNOS_1_1Model_1_1LookupTable" ],
        [ "MessageDefinition", "classBPMNOS_1_1Model_1_1MessageDefinition.html", "classBPMNOS_1_1Model_1_1MessageDefinition" ],
        [ "Model", "classBPMNOS_1_1Model_1_1Model.html", "classBPMNOS_1_1Model_1_1Model" ],
        [ "Operator", "classBPMNOS_1_1Model_1_1Operator.html", "classBPMNOS_1_1Model_1_1Operator" ],
        [ "Parameter", "classBPMNOS_1_1Model_1_1Parameter.html", "classBPMNOS_1_1Model_1_1Parameter" ],
        [ "PendingDisclosure", "structBPMNOS_1_1Model_1_1PendingDisclosure.html", "structBPMNOS_1_1Model_1_1PendingDisclosure" ],
        [ "Restriction", "classBPMNOS_1_1Model_1_1Restriction.html", "classBPMNOS_1_1Model_1_1Restriction" ],
        [ "Scenario", "classBPMNOS_1_1Model_1_1Scenario.html", "classBPMNOS_1_1Model_1_1Scenario" ],
        [ "SequentialAdHocSubProcess", "classBPMNOS_1_1Model_1_1SequentialAdHocSubProcess.html", "classBPMNOS_1_1Model_1_1SequentialAdHocSubProcess" ],
        [ "Signal", "classBPMNOS_1_1Model_1_1Signal.html", "classBPMNOS_1_1Model_1_1Signal" ],
        [ "StaticDataProvider", "classBPMNOS_1_1Model_1_1StaticDataProvider.html", "classBPMNOS_1_1Model_1_1StaticDataProvider" ],
        [ "StaticScenario", "classBPMNOS_1_1Model_1_1StaticScenario.html", "classBPMNOS_1_1Model_1_1StaticScenario" ],
        [ "StochasticDataProvider", "classBPMNOS_1_1Model_1_1StochasticDataProvider.html", "classBPMNOS_1_1Model_1_1StochasticDataProvider" ],
        [ "StochasticPendingDisclosure", "structBPMNOS_1_1Model_1_1StochasticPendingDisclosure.html", "structBPMNOS_1_1Model_1_1StochasticPendingDisclosure" ],
        [ "StochasticScenario", "classBPMNOS_1_1Model_1_1StochasticScenario.html", "classBPMNOS_1_1Model_1_1StochasticScenario" ],
        [ "Timer", "classBPMNOS_1_1Model_1_1Timer.html", "classBPMNOS_1_1Model_1_1Timer" ]
      ] ],
      [ "CollectionRegistry", "structBPMNOS_1_1CollectionRegistry.html", "structBPMNOS_1_1CollectionRegistry" ],
      [ "CSVReader", "classBPMNOS_1_1CSVReader.html", "classBPMNOS_1_1CSVReader" ],
      [ "ExpectedValueFactory", "classBPMNOS_1_1ExpectedValueFactory.html", "classBPMNOS_1_1ExpectedValueFactory" ],
      [ "InputEncoder", "classBPMNOS_1_1InputEncoder.html", "classBPMNOS_1_1InputEncoder" ],
      [ "is_vector", "structBPMNOS_1_1is__vector.html", null ],
      [ "is_vector< std::vector< T, Allocator > >", "structBPMNOS_1_1is__vector_3_01std_1_1vector_3_01T_00_01Allocator_01_4_01_4.html", null ],
      [ "RandomDistributionFactory", "classBPMNOS_1_1RandomDistributionFactory.html", "classBPMNOS_1_1RandomDistributionFactory" ],
      [ "SharedValues", "structBPMNOS_1_1SharedValues.html", "structBPMNOS_1_1SharedValues" ],
      [ "StringRegistry", "structBPMNOS_1_1StringRegistry.html", "structBPMNOS_1_1StringRegistry" ],
      [ "tuple_map", "classBPMNOS_1_1tuple__map.html", "classBPMNOS_1_1tuple__map" ],
      [ "Values", "structBPMNOS_1_1Values.html", "structBPMNOS_1_1Values" ],
      [ "vector_map", "classBPMNOS_1_1vector__map.html", "classBPMNOS_1_1vector__map" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< BPMNOS_NUMBER_TYPE >", "structstd_1_1hash_3_01BPMNOS__NUMBER__TYPE_01_4.html", "structstd_1_1hash_3_01BPMNOS__NUMBER__TYPE_01_4" ],
      [ "hash< const BPMNOS_NUMBER_TYPE >", "structstd_1_1hash_3_01const_01BPMNOS__NUMBER__TYPE_01_4.html", "structstd_1_1hash_3_01const_01BPMNOS__NUMBER__TYPE_01_4" ]
    ] ],
    [ "XML", "namespaceXML.html", [
      [ "bpmnos", "namespaceXML_1_1bpmnos.html", [
        [ "attribute", "classXML_1_1bpmnos_1_1attribute.html", "classXML_1_1bpmnos_1_1attribute" ],
        [ "attributes", "classXML_1_1bpmnos_1_1attributes.html", "classXML_1_1bpmnos_1_1attributes" ],
        [ "content", "classXML_1_1bpmnos_1_1content.html", "classXML_1_1bpmnos_1_1content" ],
        [ "decision", "classXML_1_1bpmnos_1_1decision.html", "classXML_1_1bpmnos_1_1decision" ],
        [ "decisions", "classXML_1_1bpmnos_1_1decisions.html", "classXML_1_1bpmnos_1_1decisions" ],
        [ "guidance", "classXML_1_1bpmnos_1_1guidance.html", "classXML_1_1bpmnos_1_1guidance" ],
        [ "loopCharacteristics", "classXML_1_1bpmnos_1_1loopCharacteristics.html", "classXML_1_1bpmnos_1_1loopCharacteristics" ],
        [ "message", "classXML_1_1bpmnos_1_1message.html", "classXML_1_1bpmnos_1_1message" ],
        [ "messages", "classXML_1_1bpmnos_1_1messages.html", "classXML_1_1bpmnos_1_1messages" ],
        [ "operator_", "classXML_1_1bpmnos_1_1operator__.html", "classXML_1_1bpmnos_1_1operator__" ],
        [ "operators", "classXML_1_1bpmnos_1_1operators.html", "classXML_1_1bpmnos_1_1operators" ],
        [ "parameter", "classXML_1_1bpmnos_1_1parameter.html", "classXML_1_1bpmnos_1_1parameter" ],
        [ "restriction", "classXML_1_1bpmnos_1_1restriction.html", "classXML_1_1bpmnos_1_1restriction" ],
        [ "restrictions", "classXML_1_1bpmnos_1_1restrictions.html", "classXML_1_1bpmnos_1_1restrictions" ],
        [ "signal", "classXML_1_1bpmnos_1_1signal.html", "classXML_1_1bpmnos_1_1signal" ],
        [ "status", "classXML_1_1bpmnos_1_1status.html", "classXML_1_1bpmnos_1_1status" ],
        [ "table", "classXML_1_1bpmnos_1_1table.html", "classXML_1_1bpmnos_1_1table" ],
        [ "tables", "classXML_1_1bpmnos_1_1tables.html", "classXML_1_1bpmnos_1_1tables" ],
        [ "tAttribute", "classXML_1_1bpmnos_1_1tAttribute.html", "classXML_1_1bpmnos_1_1tAttribute" ],
        [ "tAttributes", "classXML_1_1bpmnos_1_1tAttributes.html", "classXML_1_1bpmnos_1_1tAttributes" ],
        [ "tContent", "classXML_1_1bpmnos_1_1tContent.html", "classXML_1_1bpmnos_1_1tContent" ],
        [ "tDecision", "classXML_1_1bpmnos_1_1tDecision.html", "classXML_1_1bpmnos_1_1tDecision" ],
        [ "tDecisions", "classXML_1_1bpmnos_1_1tDecisions.html", "classXML_1_1bpmnos_1_1tDecisions" ],
        [ "tGuidance", "classXML_1_1bpmnos_1_1tGuidance.html", "classXML_1_1bpmnos_1_1tGuidance" ],
        [ "timer", "classXML_1_1bpmnos_1_1timer.html", "classXML_1_1bpmnos_1_1timer" ],
        [ "tLoopCharacteristics", "classXML_1_1bpmnos_1_1tLoopCharacteristics.html", "classXML_1_1bpmnos_1_1tLoopCharacteristics" ],
        [ "tMessage", "classXML_1_1bpmnos_1_1tMessage.html", "classXML_1_1bpmnos_1_1tMessage" ],
        [ "tMessages", "classXML_1_1bpmnos_1_1tMessages.html", "classXML_1_1bpmnos_1_1tMessages" ],
        [ "tOperator", "classXML_1_1bpmnos_1_1tOperator.html", "classXML_1_1bpmnos_1_1tOperator" ],
        [ "tOperators", "classXML_1_1bpmnos_1_1tOperators.html", "classXML_1_1bpmnos_1_1tOperators" ],
        [ "tParameter", "classXML_1_1bpmnos_1_1tParameter.html", "classXML_1_1bpmnos_1_1tParameter" ],
        [ "tRestriction", "classXML_1_1bpmnos_1_1tRestriction.html", "classXML_1_1bpmnos_1_1tRestriction" ],
        [ "tRestrictions", "classXML_1_1bpmnos_1_1tRestrictions.html", "classXML_1_1bpmnos_1_1tRestrictions" ],
        [ "tSignal", "classXML_1_1bpmnos_1_1tSignal.html", "classXML_1_1bpmnos_1_1tSignal" ],
        [ "tStatus", "classXML_1_1bpmnos_1_1tStatus.html", "classXML_1_1bpmnos_1_1tStatus" ],
        [ "tTable", "classXML_1_1bpmnos_1_1tTable.html", "classXML_1_1bpmnos_1_1tTable" ],
        [ "tTables", "classXML_1_1bpmnos_1_1tTables.html", "classXML_1_1bpmnos_1_1tTables" ],
        [ "tTimer", "classXML_1_1bpmnos_1_1tTimer.html", "classXML_1_1bpmnos_1_1tTimer" ]
      ] ]
    ] ]
];