var searchData=
[
  ['packing_20problem_0',['Bin packing problem',['../bin_packing_problem.html',1,'models']]],
  ['parallel_20gateways_1',['Parallel gateways',['../token_flow_logic_parallel_gateways.html',1,'execution_logic']]],
  ['parameters_2',['Loop parameters',['../extension.html#loop-parameters',1,'']]],
  ['pickup_20and_20delivery_20problem_3',['Pickup and delivery problem',['../pickup_delivery_problem.html',1,'models']]],
  ['pickupactivity_4',['SubProcess (PickupActivity)',['../pickup_delivery_problem.html#subprocess-pickupactivity',1,'']]],
  ['pickupdeliveryproblem_5',['Collaboration (PickupDeliveryProblem)',['../pickup_delivery_problem.html#collaboration-pickupdeliveryproblem',1,'']]],
  ['pickuptrip_6',['Task (PickupTrip)',['../pickup_delivery_problem.html#task-pickuptrip',1,'']]],
  ['pickupwaitevent_7',['IntermediateCatchEvent (PickupWaitEvent)',['../pickup_delivery_problem.html#intermediatecatchevent-pickupwaitevent',1,'']]],
  ['problem_8',['problem',['../assignment_problem.html',1,'Assignment problem'],['../bin_packing_problem.html',1,'Bin packing problem'],['../earliest_arrival_problem.html',1,'Earliest arrival problem'],['../job_shop_scheduling_problem.html',1,'Job shop scheduling problem'],['../knapsack_problem.html',1,'Knapsack problem'],['../pickup_delivery_problem.html',1,'Pickup and delivery problem'],['../travelling_salesperson_problem.html',1,'Travelling salesperson problem'],['../truck_driver_scheduling_problem.html',1,'Truck driver scheduling problem'],['../vehicle_routing_problem.html',1,'Vehicle routing problem']]],
  ['problem_20travellingsalesperson_5fprocess_9',['Travelling salesperson problem (TravellingSalesperson_Process)',['../travelling_salesperson_problem.html#travelling-salesperson-problem-travellingsalesperson_process',1,'']]],
  ['process_20binprocess_10',['Bin process (BinProcess)',['../bin_packing_problem.html#bin-process-binprocess',1,'']]],
  ['process_20clientprocess_11',['Client process (ClientProcess)',['../assignment_problem.html#client-process-clientprocess',1,'']]],
  ['process_20customerprocess_12',['process CustomerProcess',['../pickup_delivery_problem.html#customer-process-customerprocess',1,'Customer process (CustomerProcess)'],['../vehicle_routing_problem.html#customer-process-customerprocess-1',1,'Customer process (CustomerProcess)']]],
  ['process_20earliestarrival_5fprocess_13',['Process (EarliestArrival_Process)',['../earliest_arrival_problem.html#process-earliestarrival_process',1,'']]],
  ['process_20itemprocess_14',['process ItemProcess',['../bin_packing_problem.html#item-process-itemprocess',1,'Item process (ItemProcess)'],['../knapsack_problem.html#item-process-itemprocess-1',1,'Item process (ItemProcess)']]],
  ['process_20knapsackprocess_15',['Knapsack process (KnapsackProcess)',['../knapsack_problem.html#knapsack-process-knapsackprocess',1,'']]],
  ['process_20machineprocess_16',['Machine process (MachineProcess)',['../job_shop_scheduling_problem.html#machine-process-machineprocess',1,'']]],
  ['process_20orderprocess_17',['Order process (OrderProcess)',['../job_shop_scheduling_problem.html#order-process-orderprocess',1,'']]],
  ['process_20serverprocess_18',['Server process (ServerProcess)',['../assignment_problem.html#server-process-serverprocess',1,'']]],
  ['process_20truckdriverprocess_19',['U.S. Truck driver process (TruckDriverProcess)',['../truck_driver_scheduling_problem.html#us-truck-driver-process-truckdriverprocess',1,'']]],
  ['process_20vehicleprocess_20',['process VehicleProcess',['../pickup_delivery_problem.html#vehicle-process-vehicleprocess',1,'Vehicle process (VehicleProcess)'],['../vehicle_routing_problem.html#vehicle-process-vehicleprocess-1',1,'Vehicle process (VehicleProcess)']]],
  ['processes_21',['Processes',['../elements.html#ref-bpmnprocess-processes',1,'&lt;a class=&quot;elRef&quot; href=&quot;https://bpmn-os.github.io/bpmnpp/classBPMN_1_1Process.html&quot;&gt;Processes&lt;/a&gt;'],['../token_flow_logic_processes.html',1,'Processes']]],
  ['provider_22',['provider',['../bpmnos.html#dynamic-data-provider',1,'Dynamic data provider'],['../bpmnos.html#expected-value-data-provider',1,'Expected value data provider'],['../bpmnos.html',1,'Model provider'],['../bpmnos.html#static-data-provider',1,'Static data provider'],['../bpmnos.html#stochastic-data-provider',1,'Stochastic data provider']]]
];
